In [1]:
import pandas as pd
import numpy as np

In [2]:
filename = 'diabetes_dataset.csv'
df = pd.read_csv(filename)
df.head(1)

,age,gender,ethnicity,education_level,income_level,employment_status,smoking_status,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,...,hdl_cholesterol,ldl_cholesterol,triglycerides,glucose_fasting,glucose_postprandial,insulin_level,hba1c,diabetes_risk_score,diabetes_stage,diagnosed_diabetes
0,58,Male,Asian,Highschool,Lower-Middle,Employed,Never,0,215,5.7,...,41,160,145,136,236,6.36,8.18,29.6,Type 2,1

In [3]:
df['systolic_diastolic_ratio'] = df['systolic_bp'] / df['diastolic_bp']
df['hdl_ldl_ratio'] = df['hdl_cholesterol'] / df['ldl_cholesterol']
df['glucose_after_eating_to_fasting_ratio'] = df['glucose_postprandial'] / df['glucose_fasting']
df ['bmi_to_age_ratio'] = df['bmi'] / df['age']
df['bmi_cholesterol_ratio'] = df['bmi'] / df['cholesterol_total']

In [4]:
input_cols = ['age', 'gender','smoking_status', 'alcohol_consumption_per_week',
       'sleep_hours_per_day' , 'family_history_diabetes', 'hypertension_history',
       'cardiovascular_history', 'bmi','cholesterol_total' , 'triglycerides', 'insulin_level', 'hba1c', 
       'physical_activity_minutes_per_week', 'diet_score',
       'systolic_diastolic_ratio', 'hdl_ldl_ratio',
       'glucose_after_eating_to_fasting_ratio', 'bmi_to_age_ratio',
       'bmi_cholesterol_ratio']

target_col = 'diabetes_stage'

In [5]:
numerical_cols = df[input_cols].select_dtypes(include=['int64', 'float64']).columns.tolist()
cat_cols = df[input_cols].select_dtypes(include=['object']).columns.tolist()

In [6]:
from sklearn.model_selection import train_test_split
X = df[input_cols]
y = df[target_col]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
X_train.shape, X_test.shape

((90000, 20), (10000, 20))

In [7]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe.fit(X_train[cat_cols])
ohe.categories_

[array(['Female', 'Male', 'Other'], dtype=object),
 array(['Current', 'Former', 'Never'], dtype=object)]

In [8]:
X_train_ohe = ohe.transform(X_train[cat_cols])
X_test_ohe = ohe.transform(X_test[cat_cols])

In [9]:
input_cols_final = numerical_cols + ohe.get_feature_names_out(cat_cols).tolist()

In [10]:
X_train_final = pd.DataFrame(X_train_ohe, columns=ohe.get_feature_names_out(cat_cols), index=X_train.index)
X_train_final[numerical_cols] = X_train[numerical_cols]
X_test_final = pd.DataFrame(X_test_ohe, columns=ohe.get_feature_names_out(cat_cols), index=X_test.index)
X_test_final[numerical_cols] = X_test[numerical_cols]
X_train_final.head()

,gender_Female,gender_Male,gender_Other,smoking_status_Current,smoking_status_Former,smoking_status_Never,age,alcohol_consumption_per_week,sleep_hours_per_day,family_history_diabetes,...,triglycerides,insulin_level,hba1c,physical_activity_minutes_per_week,diet_score,systolic_diastolic_ratio,hdl_ldl_ratio,glucose_after_eating_to_fasting_ratio,bmi_to_age_ratio,bmi_cholesterol_ratio
51994,1.0,0.0,0.0,0.0,0.0,1.0,67,2,8.9,0,...,93,14.90,5.86,34,5.0,2.015385,0.405405,1.731183,0.434328,0.125431
77540,1.0,0.0,0.0,0.0,0.0,1.0,39,1,7.1,0,...,129,3.49,6.82,95,8.6,1.739130,0.420168,1.542857,0.607692,0.119697
16382,1.0,0.0,0.0,1.0,0.0,0.0,36,5,6.1,0,...,167,15.47,7.10,419,5.0,1.585714,0.650000,1.596491,0.691667,0.141477
83439,1.0,0.0,0.0,0.0,0.0,1.0,62,1,7.2,0,...,112,13.97,7.50,55,2.6,1.686047,0.388350,1.458015,0.574194,0.189362
61618,1.0,0.0,0.0,1.0,0.0,0.0,31,3,6.8,0,...,98,7.59,7.40,138,6.1,1.541667,0.343511,1.660714,1.054839,0.151389

In [11]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train_enc = le.fit_transform(y_train)
y_test_enc  = le.transform(y_test)

In [13]:
import optuna
from lightgbm import LGBMClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score

C:\Users\KUSHANKUR\AppData\Roaming\Python\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [14]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [17]:
def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'learning_rate': trial.suggest_float('learning_rate', 0.001, 0.2, log=True),
        'max_depth': trial.suggest_int('max_depth', 2, 12),
        'num_leaves': trial.suggest_int('num_leaves', 15, 100),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'random_state': 42
    }

    model = LGBMClassifier(**params)
    score = cross_val_score(model, X_train_final, y_train_enc, cv=cv, scoring='accuracy', n_jobs=-1).mean()
    return score  # Optuna maximizes this by default if direction='maximize'

In [18]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=40, show_progress_bar=True)

# Best parameters and accuracy
print("Best parameters:", study.best_params)
print("Best CV accuracy:", study.best_value)

[I 2025-10-26 11:37:22,641] A new study created in memory with name: no-name-9803e05a-1ead-4de9-b27c-9546174f04b5
Best trial: 0. Best value: 0.883067:   2%|▎         | 1/40 [01:15<48:57, 75.31s/it]

[I 2025-10-26 11:38:37,952] Trial 0 finished with value: 0.8830666666666666 and parameters: {'n_estimators': 851, 'learning_rate': 0.03599899994059888, 'max_depth': 5, 'num_leaves': 65, 'subsample': 0.5137225354508326, 'colsample_bytree': 0.8689424579278762}. Best is trial 0 with value: 0.8830666666666666.

Best trial: 1. Best value: 0.883656:   5%|▌         | 2/40 [02:51<55:34, 87.75s/it]

[I 2025-10-26 11:40:14,404] Trial 1 finished with value: 0.8836555555555556 and parameters: {'n_estimators': 819, 'learning_rate': 0.022174246575108768, 'max_depth': 11, 'num_leaves': 64, 'subsample': 0.8911620219800837, 'colsample_bytree': 0.7276518852825433}. Best is trial 1 with value: 0.8836555555555556.

Best trial: 2. Best value: 0.885178:   8%|▊         | 3/40 [03:49<45:37, 73.99s/it]

[I 2025-10-26 11:41:12,025] Trial 2 finished with value: 0.8851777777777776 and parameters: {'n_estimators': 409, 'learning_rate': 0.007414743086174909, 'max_depth': 5, 'num_leaves': 100, 'subsample': 0.5786651307982262, 'colsample_bytree': 0.729467029540994}. Best is trial 2 with value: 0.8851777777777776.

Best trial: 2. Best value: 0.885178:  10%|█         | 4/40 [06:03<58:41, 97.81s/it]

[I 2025-10-26 11:43:26,350] Trial 3 finished with value: 0.8806333333333333 and parameters: {'n_estimators': 979, 'learning_rate': 0.06878704548798921, 'max_depth': 9, 'num_leaves': 98, 'subsample': 0.7935274244147988, 'colsample_bytree': 0.8153124943472406}. Best is trial 2 with value: 0.8851777777777776.

Best trial: 2. Best value: 0.885178:  12%|█▎        | 5/40 [07:11<50:46, 87.03s/it]

[I 2025-10-26 11:44:34,275] Trial 4 finished with value: 0.8847555555555555 and parameters: {'n_estimators': 761, 'learning_rate': 0.0035468219532569494, 'max_depth': 4, 'num_leaves': 97, 'subsample': 0.8064069672712985, 'colsample_bytree': 0.8167645541994457}. Best is trial 2 with value: 0.8851777777777776.

Best trial: 2. Best value: 0.885178:  15%|█▌        | 6/40 [08:00<41:52, 73.91s/it]

[I 2025-10-26 11:45:22,715] Trial 5 finished with value: 0.8839888888888889 and parameters: {'n_estimators': 434, 'learning_rate': 0.0028675129313922992, 'max_depth': 10, 'num_leaves': 43, 'subsample': 0.8710905236171136, 'colsample_bytree': 0.764551590232413}. Best is trial 2 with value: 0.8851777777777776.

Best trial: 6. Best value: 0.885433:  18%|█▊        | 7/40 [08:29<32:33, 59.21s/it]

[I 2025-10-26 11:45:51,659] Trial 6 finished with value: 0.8854333333333333 and parameters: {'n_estimators': 261, 'learning_rate': 0.015182690437234907, 'max_depth': 5, 'num_leaves': 62, 'subsample': 0.6961768167596791, 'colsample_bytree': 0.8872815279011586}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  20%|██        | 8/40 [09:09<28:21, 53.16s/it]

[I 2025-10-26 11:46:31,854] Trial 7 finished with value: 0.8853444444444444 and parameters: {'n_estimators': 467, 'learning_rate': 0.011591852166802034, 'max_depth': 10, 'num_leaves': 31, 'subsample': 0.5289261417267201, 'colsample_bytree': 0.5171168797248229}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  22%|██▎       | 9/40 [09:29<22:07, 42.81s/it]

[I 2025-10-26 11:46:51,922] Trial 8 finished with value: 0.8848777777777779 and parameters: {'n_estimators': 128, 'learning_rate': 0.030837488453385194, 'max_depth': 11, 'num_leaves': 84, 'subsample': 0.6955260656133527, 'colsample_bytree': 0.8243571548229196}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  25%|██▌       | 10/40 [10:15<21:58, 43.97s/it]

[I 2025-10-26 11:47:38,470] Trial 9 finished with value: 0.8848999999999998 and parameters: {'n_estimators': 661, 'learning_rate': 0.014836787561016486, 'max_depth': 3, 'num_leaves': 100, 'subsample': 0.9038048269273221, 'colsample_bytree': 0.8860837812291635}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  28%|██▊       | 11/40 [10:31<17:07, 35.42s/it]

[I 2025-10-26 11:47:54,497] Trial 10 finished with value: 0.8801111111111111 and parameters: {'n_estimators': 175, 'learning_rate': 0.1534436381790807, 'max_depth': 7, 'num_leaves': 16, 'subsample': 0.9936937877582174, 'colsample_bytree': 0.9734952314470572}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  30%|███       | 12/40 [11:07<16:34, 35.53s/it]

[I 2025-10-26 11:48:30,302] Trial 11 finished with value: 0.8849555555555554 and parameters: {'n_estimators': 325, 'learning_rate': 0.008224493974261166, 'max_depth': 8, 'num_leaves': 41, 'subsample': 0.6434580043649841, 'colsample_bytree': 0.5631439956043298}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  32%|███▎      | 13/40 [11:35<14:55, 33.15s/it]

[I 2025-10-26 11:48:57,970] Trial 12 finished with value: 0.8082777777777779 and parameters: {'n_estimators': 547, 'learning_rate': 0.0014615936015901644, 'max_depth': 2, 'num_leaves': 15, 'subsample': 0.6290226482531167, 'colsample_bytree': 0.5151344692434214}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  35%|███▌      | 14/40 [12:05<14:01, 32.38s/it]

[I 2025-10-26 11:49:28,553] Trial 13 finished with value: 0.8844222222222221 and parameters: {'n_estimators': 289, 'learning_rate': 0.006411186875315723, 'max_depth': 7, 'num_leaves': 40, 'subsample': 0.5442609970987099, 'colsample_bytree': 0.6274607573889591}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  38%|███▊      | 15/40 [13:06<17:01, 40.85s/it]

[I 2025-10-26 11:50:29,030] Trial 14 finished with value: 0.8820222222222223 and parameters: {'n_estimators': 540, 'learning_rate': 0.08351846150182962, 'max_depth': 12, 'num_leaves': 53, 'subsample': 0.721377472221327, 'colsample_bytree': 0.6463739778298486}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  40%|████      | 16/40 [13:32<14:32, 36.33s/it]

[I 2025-10-26 11:50:54,884] Trial 15 finished with value: 0.8853444444444444 and parameters: {'n_estimators': 252, 'learning_rate': 0.01521667089716035, 'max_depth': 6, 'num_leaves': 32, 'subsample': 0.6158521104563248, 'colsample_bytree': 0.9799549853575332}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  42%|████▎     | 17/40 [14:32<16:38, 43.43s/it]

[I 2025-10-26 11:51:54,808] Trial 16 finished with value: 0.8821999999999999 and parameters: {'n_estimators': 430, 'learning_rate': 0.05094376759372933, 'max_depth': 9, 'num_leaves': 70, 'subsample': 0.6803100194109141, 'colsample_bytree': 0.9074928414402299}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  45%|████▌     | 18/40 [15:27<17:11, 46.87s/it]

[I 2025-10-26 11:52:49,709] Trial 17 finished with value: 0.8409333333333333 and parameters: {'n_estimators': 612, 'learning_rate': 0.0010502016329588216, 'max_depth': 8, 'num_leaves': 27, 'subsample': 0.7559968370972799, 'colsample_bytree': 0.654947190205102}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  48%|████▊     | 19/40 [16:03<15:15, 43.60s/it]

[I 2025-10-26 11:53:25,678] Trial 18 finished with value: 0.8691111111111111 and parameters: {'n_estimators': 355, 'learning_rate': 0.0029986128201244136, 'max_depth': 5, 'num_leaves': 53, 'subsample': 0.5080300240638921, 'colsample_bytree': 0.5327019010417066}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 6. Best value: 0.885433:  50%|█████     | 20/40 [16:18<11:45, 35.27s/it]

[I 2025-10-26 11:53:41,530] Trial 19 finished with value: 0.8805 and parameters: {'n_estimators': 228, 'learning_rate': 0.010924641427067016, 'max_depth': 2, 'num_leaves': 77, 'subsample': 0.5892781844049944, 'colsample_bytree': 0.5842948144891}. Best is trial 6 with value: 0.8854333333333333.

Best trial: 20. Best value: 0.885522:  52%|█████▎    | 21/40 [17:00<11:46, 37.18s/it]

[I 2025-10-26 11:54:23,160] Trial 20 finished with value: 0.8855222222222222 and parameters: {'n_estimators': 479, 'learning_rate': 0.005082590397179811, 'max_depth': 12, 'num_leaves': 26, 'subsample': 0.6568567589536585, 'colsample_bytree': 0.9325224800427339}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  55%|█████▌    | 22/40 [17:45<11:51, 39.52s/it]

[I 2025-10-26 11:55:08,145] Trial 21 finished with value: 0.8854555555555554 and parameters: {'n_estimators': 489, 'learning_rate': 0.004831391771993425, 'max_depth': 12, 'num_leaves': 25, 'subsample': 0.6855342547933775, 'colsample_bytree': 0.9288797067037606}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  57%|█████▊    | 23/40 [18:40<12:30, 44.15s/it]

[I 2025-10-26 11:56:03,078] Trial 22 finished with value: 0.885511111111111 and parameters: {'n_estimators': 654, 'learning_rate': 0.0045178631155024865, 'max_depth': 12, 'num_leaves': 23, 'subsample': 0.6577040337947627, 'colsample_bytree': 0.9308015479471714}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  60%|██████    | 24/40 [19:38<12:54, 48.42s/it]

[I 2025-10-26 11:57:01,452] Trial 23 finished with value: 0.8853222222222221 and parameters: {'n_estimators': 683, 'learning_rate': 0.004874625252260019, 'max_depth': 12, 'num_leaves': 23, 'subsample': 0.656731552862588, 'colsample_bytree': 0.9405511404770295}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  62%|██████▎   | 25/40 [20:25<11:57, 47.83s/it]

[I 2025-10-26 11:57:47,901] Trial 24 finished with value: 0.8842444444444444 and parameters: {'n_estimators': 527, 'learning_rate': 0.0019329280403187813, 'max_depth': 12, 'num_leaves': 21, 'subsample': 0.7397446699123658, 'colsample_bytree': 0.936376761387907}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  65%|██████▌   | 26/40 [21:35<12:42, 54.46s/it]

[I 2025-10-26 11:58:57,839] Trial 25 finished with value: 0.8851111111111111 and parameters: {'n_estimators': 631, 'learning_rate': 0.004644839301051779, 'max_depth': 11, 'num_leaves': 33, 'subsample': 0.7843687244758359, 'colsample_bytree': 0.9948033836606749}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  68%|██████▊   | 27/40 [22:56<13:30, 62.38s/it]

[I 2025-10-26 12:00:18,699] Trial 26 finished with value: 0.8851777777777778 and parameters: {'n_estimators': 724, 'learning_rate': 0.002244891683276074, 'max_depth': 10, 'num_leaves': 47, 'subsample': 0.578315406958672, 'colsample_bytree': 0.9346068419086582}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  70%|███████   | 28/40 [23:45<11:43, 58.63s/it]

[I 2025-10-26 12:01:08,588] Trial 27 finished with value: 0.885488888888889 and parameters: {'n_estimators': 490, 'learning_rate': 0.005290583994555364, 'max_depth': 12, 'num_leaves': 36, 'subsample': 0.6615936188306394, 'colsample_bytree': 0.8457005474992828}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  72%|███████▎  | 29/40 [24:44<10:44, 58.59s/it]

[I 2025-10-26 12:02:07,067] Trial 28 finished with value: 0.8845333333333333 and parameters: {'n_estimators': 609, 'learning_rate': 0.0018756551492874944, 'max_depth': 11, 'num_leaves': 36, 'subsample': 0.6124045059904443, 'colsample_bytree': 0.839601712042729}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  75%|███████▌  | 30/40 [25:54<10:20, 62.02s/it]

[I 2025-10-26 12:03:17,089] Trial 29 finished with value: 0.8853444444444445 and parameters: {'n_estimators': 903, 'learning_rate': 0.008313886578506718, 'max_depth': 9, 'num_leaves': 19, 'subsample': 0.8342308170636518, 'colsample_bytree': 0.8584168924251938}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  78%|███████▊  | 31/40 [26:27<07:58, 53.19s/it]

[I 2025-10-26 12:03:49,684] Trial 30 finished with value: 0.885288888888889 and parameters: {'n_estimators': 366, 'learning_rate': 0.006072602975056256, 'max_depth': 12, 'num_leaves': 28, 'subsample': 0.7215525761921622, 'colsample_bytree': 0.7581739266912706}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  80%|████████  | 32/40 [27:11<06:43, 50.45s/it]

[I 2025-10-26 12:04:33,740] Trial 31 finished with value: 0.8854222222222223 and parameters: {'n_estimators': 504, 'learning_rate': 0.0040611501416346, 'max_depth': 12, 'num_leaves': 24, 'subsample': 0.652342790921563, 'colsample_bytree': 0.9149566869329185}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  82%|████████▎ | 33/40 [28:05<06:01, 51.60s/it]

[I 2025-10-26 12:05:28,019] Trial 32 finished with value: 0.8852777777777778 and parameters: {'n_estimators': 579, 'learning_rate': 0.005439784884342491, 'max_depth': 11, 'num_leaves': 36, 'subsample': 0.6772903283037794, 'colsample_bytree': 0.9510706278393793}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  85%|████████▌ | 34/40 [28:45<04:49, 48.29s/it]

[I 2025-10-26 12:06:08,605] Trial 33 finished with value: 0.8852444444444444 and parameters: {'n_estimators': 481, 'learning_rate': 0.0035748883648895934, 'max_depth': 11, 'num_leaves': 26, 'subsample': 0.5518250889263611, 'colsample_bytree': 0.8684240435488173}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  88%|████████▊ | 35/40 [29:47<04:20, 52.16s/it]

[I 2025-10-26 12:07:09,787] Trial 34 finished with value: 0.8854333333333333 and parameters: {'n_estimators': 821, 'learning_rate': 0.009327527579193045, 'max_depth': 10, 'num_leaves': 20, 'subsample': 0.7138053046870263, 'colsample_bytree': 0.7815106137537581}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  90%|█████████ | 36/40 [30:30<03:18, 49.51s/it]

[I 2025-10-26 12:07:53,120] Trial 35 finished with value: 0.8842666666666666 and parameters: {'n_estimators': 393, 'learning_rate': 0.002575313948744151, 'max_depth': 12, 'num_leaves': 49, 'subsample': 0.5986048258277687, 'colsample_bytree': 0.9095838480462486}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  92%|█████████▎| 37/40 [31:36<02:43, 54.52s/it]

[I 2025-10-26 12:08:59,309] Trial 36 finished with value: 0.8847222222222223 and parameters: {'n_estimators': 750, 'learning_rate': 0.021339525193741223, 'max_depth': 11, 'num_leaves': 29, 'subsample': 0.7602631551814241, 'colsample_bytree': 0.9634383010808564}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  95%|█████████▌| 38/40 [32:25<01:45, 52.68s/it]

[I 2025-10-26 12:09:47,696] Trial 37 finished with value: 0.839911111111111 and parameters: {'n_estimators': 460, 'learning_rate': 0.001315119151734218, 'max_depth': 10, 'num_leaves': 45, 'subsample': 0.6765748218933056, 'colsample_bytree': 0.7078255814086208}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522:  98%|█████████▊| 39/40 [33:22<00:54, 54.21s/it]

[I 2025-10-26 12:10:45,485] Trial 38 finished with value: 0.8853 and parameters: {'n_estimators': 573, 'learning_rate': 0.003590421745097545, 'max_depth': 12, 'num_leaves': 36, 'subsample': 0.6256158652382773, 'colsample_bytree': 0.8564140034761568}. Best is trial 20 with value: 0.8855222222222222.

Best trial: 20. Best value: 0.885522: 100%|██████████| 40/40 [34:11<00:00, 51.29s/it]

[I 2025-10-26 12:11:34,250] Trial 39 finished with value: 0.8851888888888888 and parameters: {'n_estimators': 669, 'learning_rate': 0.020098275368129595, 'max_depth': 11, 'num_leaves': 15, 'subsample': 0.570163967931135, 'colsample_bytree': 0.7978368029002432}. Best is trial 20 with value: 0.8855222222222222.
Best parameters: {'n_estimators': 479, 'learning_rate': 0.005082590397179811, 'max_depth': 12, 'num_leaves': 26, 'subsample': 0.6568567589536585, 'colsample_bytree': 0.9325224800427339}
Best CV accuracy: 0.8855222222222222

In [19]:
model = LGBMClassifier(
    n_estimators = 479,
    learning_rate = 0.005082590397179811,
    max_depth = 12,
    num_leaves = 26,
    subsample = 0.6568567589536585,
    colsample_bytree = 0.9325224800427339
)
model.fit(X_train_final, y_train_enc)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.011085 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3009
[LightGBM] [Info] Number of data points in the train set: 90000, number of used features: 24
[LightGBM] [Info] Start training from score -5.894136
[LightGBM] [Info] Start training from score -2.528510
[LightGBM] [Info] Start training from score -1.145809
[LightGBM] [Info] Start training from score -6.725434
[LightGBM] [Info] Start training from score -0.513663

LGBMClassifier(colsample_bytree=0.9325224800427339,
               learning_rate=0.005082590397179811, max_depth=12,
               n_estimators=479, num_leaves=26, subsample=0.6568567589536585)

In [20]:
model.score(X_test_final, y_test_enc)

0.8744